"""delete a column

Revision ID: 5080658d0a01
Revises: 13c5e1411b8b
Create Date: 2016-10-25 16:36:38.992285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5080658d0a01'
down_revision = '13c5e1411b8b'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'test1')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('test1', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    ### end Alembic commands ###
